.TH "__signlelsit" 3 "2015年 十月 26日 星期一" "Version 1.0" "dahua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__signlelsit \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SingleList\&.h>\fP
.SS "成员变量"

.in +1c
.ti -1c
.RI "\fBElemType\fP \fBdata\fP"
.br
.RI "\fI数据域 \fP"
.ti -1c
.RI "struct \fB__signlelsit\fP * \fBnext\fP"
.br
.RI "\fI指针域 \fP"
.in -1c
.SH "详细描述"
.PP 
在文件 SingleList\&.h 第 16 行定义\&.
.SH "结构体成员变量说明"
.PP 
.SS "\fBElemType\fP __signlelsit::data"

.PP
数据域 
.PP
在文件 SingleList\&.h 第 20 行定义\&.
.PP
参考自 signle_list_append(), signle_list_delete(), signle_list_get_elem(), signle_list_index() , 以及 signle_list_insert()\&.
.SS "struct \fB__signlelsit\fP* __signlelsit::next"

.PP
指针域 
.PP
在文件 SingleList\&.h 第 25 行定义\&.
.PP
参考自 signle_list_append(), signle_list_clear(), signle_list_delete(), signle_list_get_elem(), signle_list_index(), signle_list_init(), signle_list_insert(), signle_list_is_empty() , 以及 signle_list_size()\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 dahua 的 源代码自动生成\&.
