.TH "/home/laolang/git/dahua/dahua/src/cal/cal.c" 3 "2015年 十月 26日 星期一" "Version 1.0" "dahua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/laolang/git/dahua/dahua/src/cal/cal.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./\&.\&./include/cal/cal\&.h'\fP
.br

.SS "函数"

.in +1c
.ti -1c
.RI "int \fBadd\fP (int a, int b)"
.br
.RI "\fI计算两人个数之和 \fP"
.in -1c
.SH "函数说明"
.PP 
.SS "int add (int a, int b)"

.PP
计算两人个数之和 
.PP
\fB参数:\fP
.RS 4
\fIa\fP 
.br
\fIb\fP 
.RE
.PP
\fB返回:\fP
.RS 4
.RE
.PP

.PP
在文件 cal\&.c 第 3 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 dahua 的 源代码自动生成\&.
