.TH "/home/laolang/git/dahua/dahua/include/element/element.h" 3 "2015年 十月 26日 星期一" "Version 1.0" "dahua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/laolang/git/dahua/dahua/include/element/element.h \- 
.SH SYNOPSIS
.br
.PP
.SS "类型定义"

.in +1c
.ti -1c
.RI "typedef int \fBElemType\fP"
.br
.RI "\fI元素类型　 \fP"
.in -1c
.SH "详细描述"
.PP 
元素操作 
.PP
在文件 \fBelement\&.h\fP 中定义\&.
.SH "类型定义说明"
.PP 
.SS "typedef int \fBElemType\fP"

.PP
元素类型　 
.PP
在文件 element\&.h 第 11 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 dahua 的 源代码自动生成\&.
