.TH "/home/laolang/git/dahua/dahua/src/global/global.c" 3 "2015年 十月 26日 星期一" "Version 1.0" "dahua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/laolang/git/dahua/dahua/src/global/global.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./\&.\&./include/global/global\&.h'\fP
.br

.SS "变量"

.in +1c
.ti -1c
.RI "int \fBOK\fP = 1"
.br
.RI "\fI执行成功 \fP"
.ti -1c
.RI "int \fBERROR\fP = 0"
.br
.RI "\fI执行失败 \fP"
.ti -1c
.RI "int \fBTRUE\fP = 1"
.br
.RI "\fI布尔真 \fP"
.ti -1c
.RI "int \fBFALSE\fP = 0"
.br
.RI "\fI布尔假 \fP"
.in -1c
.SH "变量说明"
.PP 
.SS "int ERROR = 0"

.PP
执行失败 
.PP
在文件 global\&.c 第 5 行定义\&.
.PP
参考自 array_list_clear(), array_list_delete(), array_list_get_elem(), array_list_index(), array_list_insert(), signle_list_get_elem() , 以及 signle_list_insert()\&.
.SS "int FALSE = 0"

.PP
布尔假 
.PP
在文件 global\&.c 第 9 行定义\&.
.PP
参考自 array_list_is_empty(), signle_list_is_empty(), str_index() , 以及 str_is_empty()\&.
.SS "int OK = 1"

.PP
执行成功 
.PP
在文件 global\&.c 第 3 行定义\&.
.PP
参考自 array_list_append(), array_list_clear(), array_list_delete(), array_list_expand(), array_list_get_elem(), array_list_insert(), signle_list_append(), signle_list_clear(), signle_list_delete(), signle_list_get_elem(), signle_list_insert(), str_clear() , 以及 str_expand()\&.
.SS "int TRUE = 1"

.PP
布尔真 
.PP
在文件 global\&.c 第 7 行定义\&.
.PP
参考自 array_list_is_empty(), signle_list_is_empty(), str_index() , 以及 str_is_empty()\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 dahua 的 源代码自动生成\&.
