.TH "/home/laolang/git/dahua/dahua/src/main/main.c" 3 "2015年 十月 26日 星期一" "Version 1.0" "dahua" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/laolang/git/dahua/dahua/src/main/main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include '\&.\&./\&.\&./include/cal/cal\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./include/list/ArrayList\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./include/list/SingleList\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./include/str/str\&.h'\fP
.br

.SS "函数"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "函数说明"
.PP 
.SS "int main (void)"

.PP
在文件 main\&.c 第 8 行定义\&.
.PP
参考 __str::data, __str::size, str_assign(), str_clear(), str_compare(), str_concat(), str_copy(), str_delete(), str_index(), str_insert(), str_is_empty(), str_replace(), str_size() , 以及 str_sub()\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 dahua 的 源代码自动生成\&.
